version: '3.8'

services:
  assets:
    build:
      context: ./assets
    volumes:
      - assets-dist:/dist
    command: >
      sh -c "rm -rf /dist/* &&
             cp -r /app/assets/dist/* /dist &&
             ls -l /dist &&
             echo 'Copied files to /dist'"

  game:
    build:
      context: ./game
    volumes:
      - game-dist:/dist
    command: >
      sh -c "rm -rf /dist/* &&
             cp -r /app/game/dist/* /dist &&
             ls -l /dist &&
             echo 'Copied files to /dist'"

  dashboard:
    build:
      context: ./dashboard
    volumes:
      - dashboard-dist:/dist
    command: >
      sh -c "rm -rf /dist/* &&
             cp -r /app/dashboard/dist/* /dist &&
             ls -l /dist &&
             echo 'Copied files to /dist'"

  wiki:
    build:
      context: ./wiki
    volumes:
      - wiki-dist:/dist
    command: >
      sh -c "rm -rf /dist/* &&
             cp -r /app/wiki/.output/public/* /dist &&
             ls -l /dist &&
             echo 'Copied files to /dist'"

  database:
    image: mongo
    env_file:
      - .env.mongodb
    volumes:
      - /database/mongodb:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

  event-tracker:
    build: ./event-tracker
    depends_on:
      - database
    env_file:
      - .env.mongodb
    command: ./main
    restart: always

  webserver:
    build:
      context: ./nginx
    volumes:
      - game-dist:/usr/share/nginx/html/game:ro
      - assets-dist:/usr/share/nginx/html/assets:ro
      - dashboard-dist:/usr/share/nginx/html/dashboard:ro
      - wiki-dist:/usr/share/nginx/html/wiki:ro
    ports:
      - "80:80"
    depends_on:
      - game
      - dashboard
      - wiki
      - event-tracker
    restart: always

volumes:
  game-dist:
  dashboard-dist:
  wiki-dist:
  assets-dist:
