version: '3.8'

services:
  game:
    build:
      context: ./game
    environment:
      - FORCE_COLOR=1
    ports:
      - "3000:5173"
    volumes:
      - ./game:/app/game
      - game-dist:/app/game/dist
      - game-modules:/app/game/node_modules/
    depends_on:
      - backend
      - assets
    command: npm run dev

  type-check:
    build:
      context: ./game
      dockerfile: type-check.Dockerfile
    volumes:
      - ./game:/app/game
      - game-dist:/app/game/dist
      - game-modules:/app/game/node_modules/
    command: /bin/bash -c 'script -q -c "npm run type-check:watch" /dev/null'
    # command: npm run type-check:watch

  wiki:
    build:
      context: ./wiki
    environment:
      - FORCE_COLOR=1
    ports:
      - "3001:3000"
    volumes:
      - ./wiki:/app/wiki
      - wiki-dist:/app/wiki/dist
      - wiki-modules:/app/wiki/node_modules/
    command: npm run dev

  dashboard:
    build:
      context: ./dashboard
    environment:
      - FORCE_COLOR=1
    ports:
      - "3002:5173"
    volumes:
      - ./dashboard:/app/dashboard
      - dashboard-dist:/app/dashboard/dist
      - dashboard-modules:/app/dashboard/node_modules/
    depends_on:
      - backend
    command: npm run dev

  mongo-express:
    image: mongo-express:latest
    ports:
      - "3003:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database

  assets:
    build:
      context: ./assets
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./assets:/app/assets
      - assets-dist:/app/assets/dist
      - assets-modules:/app/assets/node_modules/
    depends_on:
      - backend
    command: npm run dev

  database:
    image: mongo:7.0.4
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env.backend
    command: mongod --quiet --logpath /dev/null

  backend:
    build: ./backend
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - go-build:/go/pkg/mod
    env_file:
      - .env.backend
    command: air

volumes:
  mongo-data:
  go-build:
  game-modules:
  game-dist:
  dashboard-modules:
  dashboard-dist:
  wiki-modules:
  wiki-dist:
  assets-modules:
  assets-dist:
