version: '3.8'

services:
  game:
    build:
      context: ./game
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./game:/app/game
      - game-modules:/app/game/node_modules/
    command: npm ci --prefer-offline

  wiki:
    build:
      context: ./wiki
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./wiki:/app/wiki
      - wiki-modules:/app/wiki/node_modules/
    command: npm ci --prefer-offline

  dashboard:
    build:
      context: ./dashboard
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./dashboard:/app/dashboard
      - dashboard-modules:/app/dashboard/node_modules/
    command: npm ci --prefer-offline

  assets:
    build:
      context: ./assets
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./assets:/app/assets
      - assets-modules:/app/assets/node_modules/
    command: npm ci --prefer-offline


volumes:
  game-modules:
  dashboard-modules:
  wiki-modules:
  assets-modules:
