# acme challenge http only
server {
    listen 80;
    server_name play-americas.com www.play-americas.com wiki.play-americas.com dashboard.play-americas.com;

    include conf.d/include/well-known.conf;
}
