package game

import (
    "math/rand"
)

var names = []string{
    "St. Augustine",
    "Santa Fe",
    "San Juan",
    "Havana",
    "Mexico City",
    "Lima",
    "Buenos Aires",
    "Santiago",
    "Bogotá",
    "Quito",
    "Caracas",
    "Montevideo",
    "Asunción",
    "Cuzco",
    "Guadalajara",
    "Puebla",
    "Cartagena",
    "Antigua Guatemala",
    "San Salvador",
    "Santo Domingo",
    "La Paz",
    "Zacatecas",
    "Veracruz",
    "Monterrey",
    "Merida",
    "San Miguel de Tucumán",
    "Cordoba",
    "Salta",
    "Santa Marta",
    "San José",
    "Panama City",
    "Managua",
    "Tegucigalpa",
    "Los Angeles",
    "San Francisco",
    "Albuquerque",
    "San Antonio",
    "Santa Cruz de la Sierra",
    "Santiago de Cuba",
    "Arequipa",
    "Quebec City",
    "Montreal",
    "New Orleans",
    "Mobile",
    "Baton Rouge",
    "Fort-de-France",
    "Saint-Denis",
    "Cayenne",
    "Port-au-Prince",
    "Saint-Louis",
    "Cap-Haïtien",
    "Fort-de-France",
    "Saint-Pierre",
    "Pointe-à-Pitre",
    "Basse-Terre",
    "Marigot",
    "Gustavia",
    "Louisbourg",
    "Trois-Rivières",
    "Fort Albany",
    "Detroit",
    "Sainte Genevieve",
    "Vincennes",
    "Kaskaskia",
    "Biloxi",
    "La Mobile",
    "Plaisance",
    "Louisbourg",
    "Fort Caroline",
    "Akaroa",
    "Jamestown",
    "Plymouth",
    "Boston",
    "Philadelphia",
    "New York City",
    "Charleston",
    "Baltimore",
    "Newport",
    "Savannah",
    "Williamsburg",
    "Providence",
    "Annapolis",
    "New Haven",
    "Port Royal",
    "Bridgetown",
    "St. John's",
    "Nassau",
    "Basseterre",
    "Georgetown",
    "Belize City",
    "Halifax",
    "St. George's",
    "Kingston",
    "Frederiksted",
    "Saint John",
    "Quebec City",
    "Montreal",
    "Falmouth",
    "Spanish Town",
    "Castries",
}

// picks a random name
func pickName() string {
    randomIndex := rand.Intn(len(names))

    return names[randomIndex]
}

